name: Day 14 â€“ Frontend CI (Biswojit)

on:
  push:
    branches: [biswojit]
    paths:
      - "Biswojit_11/Day-14-frontend-ci/**"

  pull_request:
    branches: [main]
    paths:
      - "Biswojit_11/Day-14-frontend-ci/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: Biswojit_11/Day-14-frontend-ci
        run: npm install

      - name: Build frontend
        working-directory: Biswojit_11/Day-14-frontend-ci
        run: npm run build
